import React from "react";
import Icon1 from "../../servicesICON/ICONS-01";
import Icon2 from "../../servicesICON/ICONS-02";
import Icon3 from "../../servicesICON/ICONS-03";
import Icon4 from "../../servicesICON/ICONS-04";
import Icon5 from "../../servicesICON/ICONS-05";
import Icon6 from "../../servicesICON/ICONS-06";
// const slider = [
//   { img: "ADL SLIDE SHOW/1920/ADL MP-2.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-5.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-7.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-8.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-9.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-10.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-11.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-12.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-14.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-22.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-23.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-24.jpg" },
//   { img: "ADL SLIDE SHOW/1920/ADL MP-32.jpg" },
// ];
export const moreservices = [
  {
    name1: "EXODE",
    name3: "architecture",
    gif: <Icon1 width={200} />,
    img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-1.jpg",
    slider: [
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-1.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-2.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-3.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-4.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-5.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-6.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-7.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-8.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-9.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-10.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-11.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-12.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-13.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-14.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-15.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-16.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-17.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-18.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-19.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-20.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-21.jpg" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-22.jpg" },
    ],
  },
  {
    name1: "ENDODE",
    name3: "interiors",
    gif: <Icon2 width={200} />,
    img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-1.jpg",
    slider: [
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-1.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-2.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-3.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-4.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-5.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-6.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-7.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-8.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-9.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-10.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-11.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-12.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-13.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-14.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-15.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-16.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-17.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-18.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-19.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-20.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-21.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-23.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-24.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-25.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-26.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-27.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-28.jpg" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-29.jpg" },
    ],
  },
  {
    name1: "KARGAH",
    gif: <Icon3 width={200} />,
    name3: "product design",
    img1: "ServicePICTURES/D-KARGAH/KARGAH-1.jpg",
    slider: [
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-1.jpg" },
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-2.jpg" },
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-3.jpg" },
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-4.jpg" },
    ],
  },
  {
    name1: "CONDE",
    gif: <Icon4 width={200} />,
    name3: "construction & maintinance",
    img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-1.jpg",
    slider: [
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-1.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-2.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-3.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-4.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-5.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-6.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-7.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-8.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-9.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-10.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-11.jpg" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-12.jpg" },
    ],
  },
  {
    name1: "AID",
    gif: <Icon5 width={200} />,
    name3: "brand design",
    img1: "ServicePICTURES/E-AID/AID-1.jpg",
    slider: [
      { img1: "ServicePICTURES/E-AID/AID-1.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-2.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-3.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-4.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-5.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-6.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-7.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-8.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-9.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-10.jpg" },
      { img1: "ServicePICTURES/E-AID/AID-11.jpg" },
    ],
  },
  {
    name1: "AUX",
    gif: <Icon6 width={200} />,
    name3: "ux design",
    img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-01.jpg",
    slider: [
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-01.jpg" },
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-02.jpg" },
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-03.jpg" },
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-04.jpg" },
    ],
  },
];
