import React from "react";
import Icon1 from "../../servicesICON/ICONS-01";
import Icon2 from "../../servicesICON/ICONS-02";
import Icon3 from "../../servicesICON/ICONS-03";
import Icon4 from "../../servicesICON/ICONS-04";
import Icon5 from "../../servicesICON/ICONS-05";
import Icon6 from "../../servicesICON/ICONS-06";

export const moreservices = [
  {
    name1: "EXODE",
    name3: "architecture",
    gif: <Icon1 width={200} />,
    img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-1.webp",
    text: "We offer a range of services related to building design and planning, including site analysis, feasibility studies, schematic design, construction documents, and construction administration. We work closely with our clients to understand their needs and develop creative solutions that meet their specific requirements.",
    slider: [
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-1.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-2.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-3.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-4.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-5.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-6.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-7.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-8.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-9.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-10.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-11.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-12.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-13.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-14.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-15.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-16.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-17.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-18.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-19.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-20.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-21.webp" },
      { img1: "ServicePICTURES/B-EXODE/EXODE FINAL/EXODE-22.webp" },
    ],
  },
  {
    name1: "ENDODE",
    name3: "interiors",
    gif: <Icon2 width={200} />,
    img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-1.webp",
    text: "Our Interior design services include residential, commercial interiors, hospitality spaces, and institutions. Our bespoke design service provides a curated selection of colours, materials, and furnishings that create a cohesive and functional space while reflecting the client's personality and style.",
    slider: [
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-1.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-2.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-3.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-4.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-5.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-6.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-7.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-8.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-9.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-10.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-11.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-12.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-13.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-14.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-15.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-16.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-17.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-18.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-19.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-20.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-21.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-23.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-24.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-25.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-26.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-27.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-28.webp" },
      { img1: "ServicePICTURES/C-ENDODE/ENDODE FINAL/ENDODE-29.webp" },
    ],
  },
  {
    name1: "KARGAH",
    gif: <Icon3 width={200} />,
    name3: "product design",
    img1: "ServicePICTURES/D-KARGAH/KARGAH-1.webp",
    text: "Our product design service offers designing and prototyping bespoke products for our clients. We identify our user needs, research materials and manufacturing processes. We work closely with our clients to understand their requirements and develop innovative solutions that meet their needs.",
    slider: [
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-1.webp" },
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-2.webp" },
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-3.webp" },
      { img1: "ServicePICTURES/D-KARGAH/KARGAH-4.webp" },
    ],
  },
  {
    name1: "CONDE",
    gif: <Icon4 width={200} />,
    name3: "construction & maintinance",
    img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-1.webp",
    text: "Our construction services include the physical building of structures, including everything from laying foundations to installing electrical and plumbing systems. We work on projects ranging from small renovations to large commercial buildings. We also manage the construction process, ensuring that the project is completed on time and within budget. We are committed to delivering the final product that meets the client's specifications.",
    slider: [
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-1.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-2.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-3.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-4.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-5.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-6.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-7.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-8.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-9.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-10.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-11.webp" },
      { img1: "ServicePICTURES/A-CONDE/CONDE FINAL/CONDE-12.webp" },
    ],
  },
  {
    name1: "AID",
    gif: <Icon5 width={200} />,
    name3: "brand design",
    img1: "ServicePICTURES/E-AID/AID-1.webp",
    text: "We specialise in developing bold brand identities with bespoke logo, colour scheme, and other visual elements that help brands differentiate from their competitors. We work closely with our clients to understand their brand values and develop identities that communicate their values effectively.",
    slider: [
      { img1: "ServicePICTURES/E-AID/AID-1.webp" },
      { img1: "ServicePICTURES/E-AID/AID-2.webp" },
      { img1: "ServicePICTURES/E-AID/AID-3.webp" },
      { img1: "ServicePICTURES/E-AID/AID-4.webp" },
      { img1: "ServicePICTURES/E-AID/AID-5.webp" },
      { img1: "ServicePICTURES/E-AID/AID-6.webp" },
      { img1: "ServicePICTURES/E-AID/AID-7.webp" },
      { img1: "ServicePICTURES/E-AID/AID-8.webp" },
      { img1: "ServicePICTURES/E-AID/AID-9.webp" },
      { img1: "ServicePICTURES/E-AID/AID-10.webp" },
      { img1: "ServicePICTURES/E-AID/AID-11.webp" },
    ],
  },
  {
    name1: "AUX",
    gif: <Icon6 width={200} />,
    name3: "ux design",
    img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-01.webp",
    text: "We create digital interfaces and design User experiences (UX) that are intuitive and easy to use. Our services include websites, mobile apps, and software interfaces. We understand the user needs to create wireframes, prototypes and conduct user testing to ensure that the final product is easy to use and meets the client's requirements.",
    slider: [
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-01.webp" },
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-02.webp" },
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-03.webp" },
      { img1: "ServicePICTURES/F-AUX/AUX FINAL/AUX A-04.webp" },
    ],
  },
];
