import React from "react";

export const cards = [
  {
    name: "DR. YOUSUF RESIDENCE",
    design: " ARCHITECTURE / INTERIORS / CONSTRUCTION",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2022",
    img: "ADL PROJECTS/01-ZILAL/ZILAL-1.jpg",
    status: "BUILT",
    area: "10,500 M2",
    category: "RESIDENTIAL DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "ABDULLAH ALASHI",
    slider: [
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-1.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-2.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-4.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-5.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-6.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-9.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-11.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-12.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-13.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-14.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-16.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-17.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-18.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-19.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-20.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-21.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-22.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-23.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-24.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-26.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-27.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-29.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-31.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-32.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-33.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-34.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-35.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-36.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-37.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-38.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-39.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-40.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-41.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-42.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-43.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-44.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-45.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-46.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-48.jpg" },
      { img1: "ADL PROJECTS/01-ZILAL/ZILAL-49.jpg" },
    ],
    disc: "ZILAL (A Blissful Shade). A modern interpretation of the traditional Hejazi architecture. Elements such as courtyards, mashrabiyas and overhangs are studied and reinterpreted to adapt to the environmental factors. The primary architectural goal was to seamlessly integrate the landscape throughout the house. In contrast to the traditional approach of a front garden and recessed building mass, the building is surrounded with landscape to create features ranging from intimate seating areas to larger landscape elements. The landscape creates opportunities for views and uses for the family throughout the layout. The orientation of the building takes advantage of indirect sunlight. Whereas direct sun exposure is addressed architecturally by creating overhangs and louvres. This provides privacy as well as helps with passive cooling of the house thus reducing the reliance on air conditioning.",
  },
  {
    name: "SARHAN VILLA",
    design: "  ARCHITECTURE  / CONSTRUCTION",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2022",
    img: "ADL PROJECTS/02-SARHAN VILLA/SARHAN VILLA-1.jpg",
    slider: [
      { img1: "ADL PROJECTS/02-SARHAN VILLA/SARHAN VILLA-1.jpg" },
      { img1: "ADL PROJECTS/02-SARHAN VILLA/SARHAN VILLA-2.jpg" },
      { img1: "ADL PROJECTS/02-SARHAN VILLA/SARHAN VILLA-3.jpg" },
      { img1: "ADL PROJECTS/02-SARHAN VILLA/SARHAN VILLA-4.jpg" },
    ],
    status: "BUILT",
    area: "625 M2",
    category: "RESIDENTIAL DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "ABDULLAH ALASHI",
    disc: "",
  },
  {
    name: "DHL OFFICE",
    design: "INTERIOR DESIGN / FITOUTS / EXECUTION",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2022",
    img: "ADL PROJECTS/03-DHL JEDDAH/DHL-1.jpg",
    status: "BUILT",
    area: "250 M2",
    category: "OFFICE DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "ABDULLAH ALASHI",
    slider: [
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-1.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-2.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-3.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-4.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-5.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-6.jpg " },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-7.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-8.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-9.jpg " },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-10.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-11.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-12.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-13.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-14.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-15.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-16.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-17.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-18.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-19.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-20.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-21.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-22.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-23.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-24.jpg" },
      { img1: "ADL PROJECTS/03-DHL JEDDAH/DHL-25.jpg" },
    ],
    disc: "The office space is designed to create a positive work environment while embodying the brand identity of DHL in the spatial experience of their head office in Jeddah. The Industrial aesthetic is paired with greenery and lively colour scheme creating a unique character. The open layout provides a collaborative work environment where the bold ribbon acts as a spatial divider that defines the space without creating a physical boundary. ",
  },
  {
    name: "ASIAN HUB",
    design: "INTERIOR DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2022",
    img: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-1.jpg",
    status: "COMPLETE",
    area: "300 M2",
    category: "RESTAURANT DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-1.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-2.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-3.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-4.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-5.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-6.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-7.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-8.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-9.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-10.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-11.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-12.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-13.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-14.jpg" },
      { img1: "ADL PROJECTS/04-ASIAN HUB/ASIAN HUB-15.jpg" },
    ],
    disc: "Asian street markets are a melting pot of culture, food and urban life that truly becomes the core of the city experience. The design celebrates the spirit of Asian street markets in the dining experience of the fast casual restaurant, Asian Hub located in Jeddah. Inspired by the Tori gate the façade is a playful combination of Asian architectural elements paired with the brand identity of Asian Hub. The Dragon ceiling is the main anchoring element, it is inspired by the Duanwu Festival that is parametrically translated into a ceiling installation. The dragon ceiling, along with the sign boards become an architectural expression of Asian markets. The environmental graphics further emphasize the experience through a seamless integration of the brand identity with architecture.",
  },
  {
    name: "NINA SALON",
    design: "INTERIOR DESIGN / BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2021",
    img: "ADL PROJECTS/05-NINA SALON/NINA-1.jpg",
    status: "COMPLETE",
    area: "800 M2",
    category: "SALON DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-1.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-2.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-3.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-4.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-5.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-6.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-7.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-8.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-9.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-10.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-11.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-12.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-13.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-14.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-15.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-16.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-18.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-19.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-20.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-21.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-22.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-23.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-24.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-25.jpg" },
      { img1: "ADL PROJECTS/05-NINA SALON/NINA-26.jpg" },
    ],
    disc: "Nina is an upscale beauty salon based in Jeddah. The design intent aims to reminisce the postmodern aesthetic with a minimalist approach. Mediterranean colours and textures are used to create warmth and contextualize the overall design proposal. ",
  },
  {
    name: "QANTARA",
    design: "ARCHITECTURE / INTERIOR DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2021",
    img: "ADL PROJECTS/06-QANTARA/QNT-1.jpg",
    status: "COMPLETE",
    area: "300 M2",
    category: "RESIDENTIAL DESIGN",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    disc: "Qantara (Arches). The villa is designed as a series of interlinked spaces. The formal and spatial transitions celebrate the idea of a third place. Arches open alternative paths through the interiors and connect the spaces of the villa resulting in a collage of an architectural time capsule.  ",
    slider: [
      { img1: "ADL PROJECTS/06-QANTARA/QNT-1.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-2.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-3.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-4.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-5.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-6.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-7.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-8.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-9.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-10.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-11.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-12.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-13.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-14.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-15.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-16.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-17.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-18.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-19.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-20.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-21.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-22.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-23.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-24.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-25.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-26.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-27.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-28.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-29.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-30.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-31.jpg" },
      { img1: "ADL PROJECTS/06-QANTARA/QNT-32.jpg" },
    ],
  },
  {
    name: "TAIF VILLA",
    design: "ARCHITECTURE / INTERIOR DESIGN",
    location: "TAIF, SAUDI ARABIA",
    year: "2021",
    img: "ADL PROJECTS/07-MIHWAR/MIHWAR-1.jpg",
    status: "COMPLETE",
    area: "700 M2",
    category: "RESIDENTIAL DESIGN",
    principle: "ZAIN ANSARI, TAMER KHALIL ",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    disc: "MIHWAR (Axis). Inspired by Taif’s unique geophysical character, the dark stone walls anchor the architecture of the villa creating an architectonic interplay of planes and masses. Whereas the overall design embodies our studio’s core ideology of regional minimalism tailored to client’s specificities.",
    slider: [
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-1.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-2.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-3.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-4.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-5.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-6.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-7.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-8.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-9.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-10.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-11.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-12.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-13.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-14.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-15.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-16.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-17.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-18.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-19.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-20.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-21.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-22.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-23.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-24.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-25.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-26.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-27.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-28.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-29.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-30.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-31.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-32.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-33.jpg" },
      { img1: "ADL PROJECTS/07-MIHWAR/MIHWAR-34.jpg" },
    ],
  },
  {
    name: "SHANAB",
    design: "ARCHITECTURE / INTERIOR DESIGN / BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2021",
    img: "ADL PROJECTS/08-SHANAB/SHANAB-1.jpg",
    status: "COMPLETE",
    area: "150 M2",
    category: "RETAIL DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-1.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-2.jpeg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-3.jpeg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-4.jpeg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-5.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-6.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-7.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-8.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-9.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-10.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-11.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-12.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-13.jpg" },
      { img1: "ADL PROJECTS/08-SHANAB/SHANAB-14.jpg" },
    ],
    disc: "Traditional patterns are explored through a modern scope to establish a bold brand identity and spatial experience of a men’s clothing retail store in Jeddah.",
  },
  {
    name: "RESIDENTIAL COMPOUND",
    design: "ARCHITECTURE / INTERIOR DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2020",
    img: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-1.jpg",
    status: "COMPLETE",
    area: "32,000 M2",
    category: "RESIDENTIAL DESIGN",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-1.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-2.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-3.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-4.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-5.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-6.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-7.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-8.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-9.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-10.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-11.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-12.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-13.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-14.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-15.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-16.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-17.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-18.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-19.jpg" },
      { img1: "ADL PROJECTS/09-RESIDENTIAL COMPOUND/RS-20.jpg" },
    ],
    disc: "From tradition to function. The environmental and social role of the Mashrabiyas remains significant to the architectural heritage of Middle Eastern architecture. The traditional window element is used as a functional ornament to provide protection from the harsh sun while re-establishing a sense of regional identity. ",
  },
  {
    name: "COMALLI",
    design: "ARCHITECTURE / INTERIOR DESIGN / BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2020",
    img: "ADL PROJECTS/10-COMALLI/COM-1.jpg",
    status: "BUILT",
    area: "600 M2",
    category: "RESTAURANT DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/10-COMALLI/COM-1.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-2.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-2A.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-2B.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-5.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-6.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-7.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-8.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-9.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-10.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-11.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-12.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-13.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-14.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-15.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-16.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-17.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-18.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-19.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-20.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-21.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-22.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-23.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-24.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-25.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-26.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-27.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-28.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-29.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-30.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-31.jpg" },
      { img1: "ADL PROJECTS/10-COMALLI/COM-32.jpg" },
    ],
    disc: "Comali is a Latin American restaurant that fuses ancient and modern recipes to create a unique culinary experience. Ancient symbols from Aztec civilisations are explored to conceptualize the architectural and brand identity of the restaurant. The logo is derived from the symbol ‘Atl’ that is a personification of life, creation, warmth and sustenance. Whereas the spatial experience bridges the ancient architectural elements with the colour blocking technique inspired by Luis Barragán work. ",
  },
  {
    name: "LION SHARE",
    design: "ARCHITECTURE / INTERIOR DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2020",
    img: "ADL PROJECTS/11-LION SHARE/LS-1.jpg",
    status: "BUILT",
    area: "200 M2",
    category: "RESTAURANT DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/11-LION SHARE/LS-1.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-2.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-3.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-4.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-5.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-6.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-7.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-8.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-9.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-10.jpg" },
      { img1: "ADL PROJECTS/11-LION SHARE/LS-11.jpg" },
    ],
    disc: "Lion’s Share is a healthy food store based in Jeddah, Saudi Arabia. Architectural ribbon is utilized as a spatial organizer that defines and connects the program with the interior space.",
  },
  {
    name: "ZAYAN",
    design: "BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2020",
    img: "ADL PROJECTS/12-GRILL HOUSE/GH-1.jpg",
    status: "BUILT",
    area: "600 M2",
    category: "RESIDENTIALDESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM",
    civil: "EL MOHANNAD GAD",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/12-GRILL HOUSE/GH-1.jpg" },
      { img1: "ADL PROJECTS/12-GRILL HOUSE/GH-2.jpg" },
      { img1: "ADL PROJECTS/12-GRILL HOUSE/GH-3.jpg" },
      { img1: "ADL PROJECTS/12-GRILL HOUSE/GH-4.jpg" },
      { img1: "ADL PROJECTS/12-GRILL HOUSE/GH-5.jpg" },
      { img1: "ADL PROJECTS/12-GRILL HOUSE/GH-6.jpg" },
    ],
    disc: "",
  },
  {
    name: "BAZA’AN",
    design: "ARCHITECTURE",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2019",
    img: "ADL PROJECTS/13- BAZA'AN/BZ1.jpg",
    status: "BUILT",
    area: "",
    category: "PUBLIC INSTALLATION DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASSIM, ZOMMAH KHAN, FARAH MUSHATAHA",
    civil: "EL MOHANNAD GAD ",
    construction: " ABDULLAH ALASHI",
    slider: [
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ1.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ2.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ3.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ4.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ5.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ6.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ7.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ8.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ9.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ10.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ11.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ12.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ13.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ14.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ15.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ16.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ17.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ18.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ19.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ20.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ21.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ22.jpg" },
      { img1: "ADL PROJECTS/13- BAZA'AN/BZ23.jpg" },
    ],
    disc: "Baza’an are traditional drinking water fountains found in the historic city of Hejaz. To revive this tradition, King Abdul Aziz water Endowment commissioned Anastomosis Design Lab to design and build 24 new Baza’ans all over the city of Jeddah. The design takes its inspiration from the history of the endowment when they laid the first pipe connecting Fatima Valley to Jeddah in order to create fresh water supply for the city. The cylindrical form of the Baza’an is intended to reminisce the concrete pipe segments used in different projects by the endowment. Baza’an Corniche located right in front of the Waterfront Mosque also features an ablution facility that can be used by worshippers",
  },
  {
    name: "AL AQEEQ SCHOOL",
    design: "ARCHITECTURE / INTERIOR DESIGN / BRAND DESIGN",
    location: "RIYADH, SAUDI ARABIA",
    year: "2019",
    img: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-1.jpg",
    status: "COMPLETE",
    area: "42,000 M2",
    category: "INSTITUTIONAL DESIGN ",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    slider: [
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-1.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-2.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-4.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-5.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-6.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-7.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-8.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-9.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-10.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-11.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-12.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-13.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-14.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-15.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-16.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-17.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-18.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-19.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-20.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-21.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-22.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-23.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-24.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-25.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-26.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-27.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-28.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-29.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-30.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-31.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-32.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-33.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-34.jpg" },
      { img1: "ADL PROJECTS/14-AL AQIQ SCHOOL/AQS-35.jpg" },
    ],
    construction: "",
    disc: "Knowledge can be defined as the understanding of information around us, acquired through questioning, discovering and learning. A successful learning environment must stimulate a subconscious triggering of information in the brain. Inspired by the paper folding art of Origami, the proposed design philosophy aims to enhance the students’ thinking process and train them to create links between the micro and macro worlds.  ",
  },
  {
    name: "KAWE SOUQ",
    design: "ARCHITECTURE",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2019",
    img: "ADL PROJECTS/15-KAWE SOUQ/KS-1.jpg",
    status: "COMPLETE",
    area: "41,000 M2",
    category: "MARKET DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "",
    civil: "EL MOHANNAD GAD",
    construction: "ADL",
    slider: [
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-1.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-2.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-3.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-4.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-6.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-7.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-8.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-9.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-10.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-11.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-12.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-13.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-14.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-15.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-16.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-17.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-18.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-19.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-20.jpg" },
      { img1: "ADL PROJECTS/15-KAWE SOUQ/KS-21.jpg" },
    ],
    disc: "Shirae can be described as the sail that was used in traditional Hejazi merchant ships. Located adjacent to the Mena Seaport, Al-Shirae Souq takes its inspiration from the sails of the traditional trading ships and the mechanics of the modern cranes used in the nearby seaport.",
  },
  {
    name: "AL JADID RESTAURANT",
    design: "ARCHITECTURE / BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2019",
    img: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-1.jpg",
    status: "COMPLETE",
    area: "",
    category: "RESTAURANT DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "",
    civil: "",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-1.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-2.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-3.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-4.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-5.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-6.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-7.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-8.jpg" },
      { img1: "ADL PROJECTS/16-AL JADID RESTAURANT/JD-9.jpg" },
    ],
    disc: "Al Jadid is restaurant that specializes in Pakistani Cuisine. The project aimed to rebrand and uplift the existing architectural identity through a façade installation. The design explores the concept of Roshan, architectural screens used in historic buildings in various parts of Pakistan. Whereas the logo is a calligraphic expression of the English and Arabic letters ‘J’ and ‘ج’.",
  },
  {
    name: "NAHR KING ABDUL AZIZ WATER ENDOWMENT MUSEUM",
    design: "INTERIOR DESIGN / FITOUT / EXECUTION",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2018",
    img: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-01.JPG",
    status: "BUILT",
    area: "500 M",
    category: "MUSEUM DESIGN",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "SOPHIA QASIM",
    civil: ": EL MOHANNAD GAD",
    construction: "ADL",
    slider: [
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-01.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-02.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-03.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-04.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-05.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-06.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-07.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-08.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-09.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-10.JPG" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-11.jpg" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-12.jpg" },
      { img1: "ADL PROJECTS/17-KAWE MUSEUM/KAWE MUSEUM-13.jpg" },
    ],
    disc: "",
  },
  {
    name: "KAWE MONUMENT",
    design: "ARCHITECTURE / INTERIOR DESIGN",
    location: "RIYADH, SAUDI ARABIA",
    year: "2018",
    img: "ADL PROJECTS/18- KAWE MONUMENT/KWM-1.jpg",
    status: "",
    area: "",
    category: "",
    principle: "",
    projectarchitech: "",
    civil: "",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-1.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-2.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-3.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-4.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-5.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-6.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-7.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-8.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-9.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-10.jpg" },
      { img1: "ADL PROJECTS/18- KAWE MONUMENT/KWM-11.jpg" },
    ],
    disc: "",
  },
  {
    name: "PLAY SCAPE",
    design: "ARCHITECTURE",
    location: "RIYADH, SAUDI ARABIA",
    year: "2018",
    img: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-00.jpg",
    status: "BUILT ",
    area: "625 M2",
    category: "PLAYSCAPE DESIGN ",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-00.JPG" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-00A.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-00B.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-00C.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-00D.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-1.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-2.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-3.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-4.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-5.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-6.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-7.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-8.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-9.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-10.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-11.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-12.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-13.jpg" },
      { img1: "ADL PROJECTS/19-PLAY SCAPE/PLAY SCAPE-14.jpg" },
    ],
    disc: "Playscapes play an integral role in the physical and cognitive development of children. The primary goal is to introduce movements that involve cognitive impulses and target specific muscle groups for children. The project aims to break the cycle of passing on poor behaviours through behavioural science and establish positive association with physical exercise. Fitness with fun.",
  },
  {
    name: "FASLA",
    design: "BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2018",
    img: "ADL PROJECTS/20-FASLA/FASLA1.jpg",
    status: "COMPLETE",
    area: "",
    category: "BRAND DESIGN ",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/20-FASLA/FASLA1.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA2.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA3.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA4.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA5.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA6.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA7.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA8.jpg" },
      { img1: "ADL PROJECTS/20-FASLA/FASLA9.jpg" },
    ],
    disc: "Fasla is the punctuation mark apostrophe in Arabic language. The project entails brand design for a mass communication firm. The brand design combines the apostrophe and dialogue box to create a bold brand expression.",
  },
  {
    name: "RIDWAN RESIDENCE",
    design: "ARCHITECTURE / INTERIOR DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2017",
    img: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR1.jpg",
    status: "BUILT ",
    area: "625 M2",
    category: "RESIDENTIAL DESIGN ",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR1.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR2.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR3.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR4.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR5.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR6.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR7.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR9.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR10.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR12.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR13.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR14.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR15.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR16.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR17.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR18.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR19.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR20.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR21.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR22.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR23.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR24.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR25.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR26.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR27.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR28.jpg" },
      { img1: "ADL PROJECTS/21-RIDWAN RESIDENCE/RR29.jpg" },
    ],
    disc: "Al Ridwan Residence explores the concept of regional minimalism through an embodiment of contextual and social references derived from the local Hejazi architecture. The L-shape configuration bifurcates the private and public wings creating an intersecting overlay of masses that blurs lines between landscape and architecture. To harness the limited availability of space the interiors are furnished with storage walls integrated seamlessly into the architecture of the house. The humble presence of the house aims to direct focus on the surrounding garden. Whereas the Earthly materials and warm tones define the peaceful atmosphere of the house. Al Ridwan residence is the perfect embodiment of a challenging budget and responsible design strategies.",
  },
  {
    name: "RED IMPACT OFFICE",
    design: "INTERIOR DESIGN ",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2017",
    img: "ADL PROJECTS/22-RED IMPACT/RI1.jpg",
    status: "BUILT",
    area: "1000 M2",
    category: "OFFICE DESIGN",
    principle: " ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    slider: [
      { img1: "ADL PROJECTS/22-RED IMPACT/RI1.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI2.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI3.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI4.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI5.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI6.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI7.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI9.jpg" },
      { img1: "ADL PROJECTS/22-RED IMPACT/RI10.jpg" },
    ],
    construction: "",
    disc: "The world of advertisement is defined by a series of messages crafted to persuade the people to consume products. These messages are short-lived illusions that are left as memories. Provocative memories that create desires. The design of Red Impact office celebrates the phenomenon of advertisement by embodying the notion of illusion and ephemerality in space. In order to physically translate the concept, anamorphic graphics were utilized to create an interesting illusion of shape shifting space. ",
  },
  {
    name: "MUSATAH",
    design: "ARCHITECTURE",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2016",
    img: "ADL PROJECTS/24-HAVEN/HAVEN-1.jpg",
    status: "",
    area: "900 M2",
    category: "RESIDENTIAL DESIGN",
    principle: "ZAIN ANSARI",
    slider: [
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-1.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-2.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-3.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-4.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-5.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-6.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-7.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-8.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-9.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-10.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-11.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-12.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-13.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-14.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-15.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-16.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-17.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-18.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-19.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-20.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-21.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-22.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-23.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-24.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-25.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-26.jpg" },
      { img1: "ADL PROJECTS/24-HAVEN/HAVEN-27.jpg" },
    ],
    projectarchitech: "",
    civil: "",
    construction: "",
    disc: "MUSATAH (planar). The concept of the house is rooted in the tectonic character of the Hejazi architecture. A set of stone walls structure the space and generates a hierarchical sequence of heights and fragmented volumes creating a play of segmented and linked zones.",
  },
  {
    name: "MARAKAZ AL AHYAA COMMUNITY CENTER",
    design: "ARCHITECTURE / INTERIOR DESIGN ",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2016",
    img: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC1.jpg",
    status: "COMPLETE (DESIGN)",
    area: "6000 M2",
    category: "COMMUNITY DESIGN",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    construction: "",
    slider: [
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC1.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC2.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC3.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC4.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC5.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC6.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC7.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC8.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC9.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC10.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC11.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC12.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC13.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC14.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC15.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC16.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC17.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC18.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC19.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC20.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC21.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC22.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC23.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC24.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC25.jpg" },
      { img1: "ADL PROJECTS/25-MARAKAZ AL AHYAA/JCC26.jpg" },
    ],
    disc: "The devolvement of any society relies heavily on finance, sociology, psychology, politics and technology. A collaboration of all the disciplines is mandatory to serve the community with a holistic approach. The aim of the community center is to provide a platform to unify all the matters of management under one roof. The primary function of the community center is to design and implement programs for the betterment of the community. The design objective is to understand and reinterpret the spirit of traditional Hejazi architecture to find functional relevance and establish a sustainable architectural identity in the global context.",
  },
  {
    name: "TEEN TOWN TOYS",
    design: "ARCHITECTURE / INTERIOR DESIGN / FITOUT / EXECUTION",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2016",
    img: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-1.jpg",
    status: "BUILT",
    area: "1500 M2",
    category: "RETAIL / COMMERICAL DESIGN ",
    principle: "ZAIN ANSARI, TAMER KHALIL",
    projectarchitech: "",
    civil: "",
    slider: [
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-1.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-2.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-3.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-4.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-5.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-6.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-7.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-9.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-10.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-11.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-12.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-13.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-14.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-15.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-16.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-17.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-18.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-19.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-20.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-21.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-22.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-23.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-24.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-25.jpg" },
      { img1: "ADL PROJECTS/23-TEEN TOWN TOYS/TTT-26.jpg" },
    ],
    construction: "EL MOHANNAD GAD",
    disc: "Understanding the psychology of children, the space of the toy store was created as a playscape. The design promotes a sense of adventure and freedom to explore.",
  },
  {
    name: "MAKI",
    design: "INTERIOR DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2016",
    img: "ADL PROJECTS/26-MAKI/MAKI1.JPG",
    status: "BUILT",
    area: "350 M2",
    category: "RESTAURANT DESIGN",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    slider: [
      { img1: "ADL PROJECTS/26-MAKI/MAKI1.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI2.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI3.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI4.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI5.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI6.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI7.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI9.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI10.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI11.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI12.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI13.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI14.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI15.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI16.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI17.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI18.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI19.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI20.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI21.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI22.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI23.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI24.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI25.JPG" },
      { img1: "ADL PROJECTS/26-MAKI/MAKI26.JPG" },
    ],
    construction: "",
    disc: "The design concept for Maki House is derived through a juxtaposition of Japanese minimalism with contemporary graphic styles. Aged concrete wall cladding and floor tiles with wooden grouting reminisces the minimalist Japanese architecture. Whereas the spaces are contrasted with paintings and graffiti expressing the contemporary Japanese pop art. The technique is inspired by the traditional Japanese art form ‘Notan’, where different color intensities are superimposed to create depth and spatial layering. The graphics are broken and printed on separate layers of glass creating a unique dynamic sensory experience.",
  },
  {
    name: "BLOOMING",
    design: "INTERIOR DESIGN / BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2016",
    img: "ADL PROJECTS/27-BLOOMING/BLOOMING-01.jpg",
    status: "COMPLETE",
    area: "200 M2",
    category: "RETAIL AND BRAND DESIGN ",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    slider: [
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-01.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-02.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-03.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-04.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-05.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-06.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-07.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-08.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-09.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-10.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-11.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-12.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-13.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-14.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-15.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-16.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-17.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-18.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-19.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-20.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-21.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-22.jpg" },
      { img1: "ADL PROJECTS/27-BLOOMING/BLOOMING-23.jpg" },
    ],
    construction: "",
    disc: "To create a spatial identity for Blooming lingerie stores, the primary objective was to contextualize the activity of selling lingerie in the local culture. In contrast to the western culture, lingerie is associated with privacy and protection rather than physical enhancement and expression of the body. To translate this concept into a physical space the design celebrates the philosophy of ‘Contained Sensuality’. The concept takes its inspiration from the traditional ‘Veil’, where the idea is to create a ",
  },
  {
    name: "LINENZA",
    design: "BRAND DESIGN",
    location: "JEDDAH, SAUDI ARABIA",
    year: "2016",
    img: "ADL PROJECTS/28-LINENZA/LINENZA-01.jpg",
    status: "COMPLETE",
    area: "",
    category: "BRAND DESIGN ",
    principle: "ZAIN ANSARI",
    projectarchitech: "",
    civil: "",
    slider: [
      { img1: "ADL PROJECTS/28-LINENZA/LINENZA-01.jpg" },
      { img1: "ADL PROJECTS/28-LINENZA/LINENZA-02.jpg" },
      { img1: "ADL PROJECTS/28-LINENZA/LINENZA-03.jpg" },
      { img1: "ADL PROJECTS/28-LINENZA/LINENZA-04.jpg" },
      { img1: "ADL PROJECTS/28-LINENZA/LINENZA-05.jpg" },
    ],
    construction: "",
    disc: "",
  },
];
